# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f1d0dee93b61d585f312397f5630741d85663f62de943d12544f8a9a0f67bd3d6d0eac13f6c33769571257e787e4819533492af7db03e11a51cd1b4a8fb5a28

test:
  secret_key_base: 5c28f6a7fd027fb22c696bacfcd8a7d58b38d84b6db6cc0fed891d22adf7b9af0cd0d3590edb18a38fc1f7e51448f24ef32fac4f036c2cb264da0e0c43f01b2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
